CREATE TABLE IF NOT EXISTS inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  engagement VARCHAR(32) NOT NULL,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(254) NOT NULL,
  company VARCHAR(150),
  phone VARCHAR(32),
  service VARCHAR(64),
  budget VARCHAR(32),
  timeline VARCHAR(32),
  message TEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'new',
  email_sent BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT inquiries_status_check
    CHECK (status IN ('new', 'reviewing', 'contacted', 'closed', 'archived'))
);

CREATE INDEX IF NOT EXISTS inquiries_created_at_idx
  ON inquiries (created_at);

CREATE INDEX IF NOT EXISTS inquiries_status_idx
  ON inquiries (status);

CREATE INDEX IF NOT EXISTS inquiries_email_idx
  ON inquiries (email);